create table avalon_execution_quest5(
matchname varchar(40),
playeronquest1 integer,
playeronquest2 integer,
playeronquest3 integer,
playeronquest4 integer,
playeronquest5 integer,
numberofsuccesses integer,
numberoffails integer,
result varchar(20),
player1execution,
player2execution,
player3execution,
player4execution,
player5execution)
