create table avalon_votes_quest1_proposal4 (
matchname varchar(40),
player1vote varchar(20),
player2vote varchar(20),
player3vote varchar(20),
player4vote varchar(20),
player5vote varchar(20),
player6vote varchar(20),
player7vote varchar(20),
player8vote varchar(20),
player9vote varchar(20),
player10vote varchar(20),
result varchar(20),
teamleader integer,
proposedplayer1 integer,
proposedplayer2 integer,
proposedplayer3 integer)